server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.200.135:3306/order_system?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: shhan
    password: Han920!@#

    hikari:
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000

    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect